plugins {
    id 'com.android.application'
}

android {
    namespace 'com.gtidev.a12e'
    compileSdk 34

    defaultConfig {
        applicationId "com.gtidev.a12e"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    signingConfigs {
        release {
            storeFile file('../keystore/a12e-release.jks')
            storePassword 'a12escale'
            keyAlias 'a12e'
            keyPassword 'a12escale'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
}
